### ISSUE TITLE
Double calendars

### ISSUE THREAD

**Issue by tommiehansen** [t1m0n/air-datepicker#121] opened 2016-09-13 11:14 UTC
Any possibility for you to add an option to have a multi-calendar view ie 2 calenderas visible at the same time? Often when picking a range of dates this is often preferred since often date1 and date2 can be in two different months.

**Comment by t1m0n** [comment] 2016-09-17 17:52
Yeah I'm planning to add this feature, but I think it will not be very soon, due to time deficit.

duplicate of #8.

**Closed by t1m0n** 2016-09-17 17:52 UTC

**Comment by wuliqiangqiang** [comment] 2018-12-12 10:18
@t1m0n hi，was it added about the range can set two calendars view?

**Comment by t1m0n** [comment] 2018-12-13 08:59
@wuliqiangqiang you could try to use version from [this ](https://github.com/t1m0n/air-datepicker/tree/multiple-cals )branch. It is not completed, but basic functionality should work.
